### ISSUE TITLE
Additional Plugins

### ISSUE THREAD

**Issue by lekkas** [balena-io-modules/scrutinizer#12]
Listing some nice-to-have plugins that came up from https://github.com/resin-io/repos/blob/master/schema.yaml

- [ ] Top Contributors
- [ ] Version (this is tricky, since version can be present in a few places (tags, package.json etc.)
- [ ] Last Commit Date
- [ ] Open Issues
- [ ] Open Pull Requests
- [ ] Has Issue template
- [ ] Has Pull Request template
- [ ] 'Health' information about codebase (e.g. test coverage)

**Comment by dimitrisnl** [comment]
@jviotti 	Want me to work on including some of these suggestions?

**Comment by jviotti** [comment]
@dimitrisnl Sounds like a great start!

**Comment by dimitrisnl** [comment]
@lekkas 	Are you ok with me closing this and opening separate issues?

**Comment by lekkas** [comment]
@dimitrisnl go for it!
